spring:
  profiles:
    group:
      local: "local,common"
      prod: "prod,common"
---
spring:
  profiles:
    active: "local"
---
spring:
  profiles:
    active: "prod"
---
spring:
  config:
    activate:
      on-profile: "common"

mybatis:
  mapper-locations: classpath:mapper/*.xml